[package]
name = "rcv-dev"
version = "0.1.0"
authors = ["bosley <bosley117@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

opencv = "0.46"
derive_more = "0.99.11"